### ISSUE TITLE
Extension is breaking Swagger

### ISSUE THREAD

**Issue by catiarodrigues** [PaylineByMonext/payline-magento-2#3]
Hello,

I've installed your extension and our store swagger stopped working.

It displays the following  error:

![screen-shot-2017-09-03-at-14 23 10](https://user-images.githubusercontent.com/5954362/30004301-95b8060e-90c4-11e7-88b5-4b8d66f94711.jpg)

I've found this post on stackexchange with the same problem (other module)
https://magento.stackexchange.com/questions/160730/magento-2-1-3-swagger-and-api-error

Can you look into this issue?

We are using Magento ver. 2.1.7 and your latest extension version.

thank you

**Comment by vegangirlthatcodes** [comment]
This issue should be closed as it was corrected with one of your updates.
