### ISSUE TITLE
ERROR for order ; payment gateway amount does not match order amount

### ISSUE THREAD

**Issue by catiarodrigues** [PaylineByMonext/payline-magento-2#5]
I have two payment methods on my store one being PaylineByMonext.

With the other payment method everything is working fine but with payline I'm having an issue with orders that have Tax applied.

Your extension if configured with the redirect option (We can't make it work correctly with the inshop option due to incompatibility with One step checkout extensions).

Here's an example of an order:

1. Add product to cart -> 12,59 € tax included
2. Go to checkout
3. On the order summary we can find this data:
3.1. **cart subtotal**	12,59 €
3.2. **Shipping**	3,47 €
3.3. **Tax**	3,00 €
3.4. **Grand total without tax**	13,06 € 
3.5. **Grand Total with tax**	16,06 €
4. We place the order and are redirected to redunicre website
5. The value charged is 13,06 €  ( Grand total without tax )
6. The order is placed as pending payment
7. we proceed with payment and the order is set to canceled
8. If we open the order in admin pan we see the **ERROR for order ; payment gateway amount does not match order amount** error.

We tried placing an order setting the address to outside of Portugal witch made the order taxfree. In this case the extension is working ok.

Let me know if you need more information.
Thank you

**Comment by PaylineGitHub** [comment]
Hello,

Tax was solved in 1.2.1 release, unfortunately tag version in composer.json was still 1.2.0
I've fixed this in 1.2.2 release, can you check your tax problem disapears with 1.2.2 ?
